export const LOGIN = 'login'
export const LOGOUT = 'logout'
export const TITLE = 'title'
export const SETUSER = 'setUser'
export const GET_CURRENTUSER_MEMBERID = 'GET_CURRENTUSER_MEMBERID'
export const RECORD_QINIUTOKEN = 'RECORD_QINIUTOKEN'
